### ISSUE TITLE
Who Downloaded Attachment not working

### ISSUE THREAD

**Issue by ghopretz** [realdigger/SMF-Who-Downloaded-Attachment#1]
![screenshot 58](https://user-images.githubusercontent.com/8053983/39684462-37917d6a-51e6-11e8-8893-fe8adcd11494.png)
![screenshot 59](https://user-images.githubusercontent.com/8053983/39684464-38cf36a4-51e6-11e8-9f15-e87fda73693d.png)

why is "Who Downloaded Attachment" not working in my Forum?

**Comment by realdigger** [comment]
Did you install mod to your custom theme? Try to switch to SMF Defaut theme.

**Comment by ghozien** [comment]
Yes, i using theme & some of mod in my smf.

**Comment by ghozien** [comment]
First time i install who downloaded attachment, it is no problem.
But after some of weeks, the problem came.
